### ISSUE TITLE
Custom Game Path

### ISSUE THREAD

**Issue by manutoo** [manhunterita/PATCH#24]
Would it be possible to have the option to change the game folder ?

For compatibility reason with my existing user base, I'd like to be able to have : "C:\MyTest" = my game ; "C:\MyTest\Launcher" = Launcher . (in that case, the patcher shouldn't delete the "Launcher" subfolder when repairing the game ;-) )

On Mac, putting it in a subfolder or in the same folder might not work (because it may require admin rights), so it would be good to be able to specify "~/Documents/MyGame" or something similar, or even the Launcher's Application.persistentDataPath folder (eg: "%LauncherData%/MyGame").

**Comment by manhunterita** [comment]
Now the API exposes ISettings, IAdminSettings and ILauncherSettings interfaces. Also, now the API always accepts interfaces instead of concrete types.
This should make it easy to implement your own settings by implementing the interfaces.
The standard settings implement those interfaces too and are already included in the DLL, so you can look at the standard implementation.

The change will be included in 2.2.2 release.
